### ISSUE TITLE
Aquivo restaurantes.json

### ISSUE THREAD

**Issue by AndresGrams** [Webschool-io/be-mean-instagram-mongodb-FAQ#2]
Boa tarde onde encontro os arquivos restaurantes.json

Ps. Hd queimou estou refazendo todas aulas.

**Comment by amandavilela** [comment]
Olá!

O link para download do arquivo encontra-se na descrição do exercício 01: https://github.com/Webschool-io/be-mean-instagram/blob/master/apostila/module-mongodb/export_import.md#exercício

**Comment by AndresGrams** [comment]
Tks Amanda..

**Comment by suissa** [comment]
https://github.com/Webschool-io/be-mean-instagram/tree/master/apostila/module-mongodb/data
