### ISSUE TITLE
Dúvida - MongoDb 2 para o 3. 

### ISSUE THREAD

**Issue by carlosmachel** [Webschool-io/be-mean-instagram-mongodb-FAQ#3]
Boa noite. 

Eu tive que ficar um tempo parado no curso. Então estou revendo as aulas. 

Na aula 1 quando é mencionado a mudança do MongoDb do 2 para o 3, eu fiquei curioso com a questão das Storage Engines. Eu fui pesquisar o que significava essa mudança que permitiria usar mais de uma.

Pelo que entendi, com essa mudança de versão você consegue ter um MongoDB trabalhando com uma storage engine que é boa para gravar informação e ao mesmo tempo uma outra instância trabalhando com uma que é rapida na leitura certo?

Será que em um futuro conseguiriamos ter a arquitetura híbrida usando apenas o MongoDb como a casca e multiplas engines por baixo atuando como diferentes NoSQL ou isso não muda sua classificação no tipo de NoSQL? 

A definição da storage engine eu li no faq do MongoDB.  https://docs.mongodb.org/v3.0/faq/storage/

**Comment by suissa** [comment]
Quem sabe no futuro sim.
Assim esperamos ehhehehe.

Porém vc nao trabalha ao mesmo tempo com 2, vc tem que escolher 1, mas claro que pode usar uma diferente em um servidor diferente.
