### ISSUE TITLE
Dúvida Shard e Réplica

### ISSUE THREAD

**Issue by leonascimento** [Webschool-io/be-mean-instagram-mongodb-FAQ#4]
@suissa  ou @wbruno a nomenclatura de pastas criadas para shard1 shard2 shard3 e/ou réplicas bem como as faixas de portas devem ser apenas essas citadas nas apostilas, podemos mudar?

Estou perguntando isso porque tentei mudar a na hora de criar um shard dá um erro.
Mas usando a nomenclatura de pastas e as portas citadas no material tudo dá certo.

Obrigado desde já aguardo essa resposta.

**Comment by wbruno** [comment]
Pode mudar sim. Só foi feito dessa forma porque estava tudo local.
Idealmente, em produção você terá 3 máquinas diferentes, e não várias instâncias na mesma.

Ai sim, temos HA. (Alta Disponibilidade), pois se uma cair, você tem a outra.
Você só precisa apontar a configuração corretamente.

**Comment by leonascimento** [comment]
Obrigado Willian vlw mesmo... :)
