### ISSUE TITLE
Indicação de Livro

### ISSUE THREAD

**Issue by leonascimento** [Webschool-io/be-mean-instagram-mongodb-FAQ#5]
@suissa  ou @wbruno vocês podem me indicar um bom livro de MongoDB que vc indicam pra valer?
Sabe não sei se estou falando besteira, mas será que próximo ano rolaria um curso de Mineração de Dados usando MongoDB?

**Comment by wbruno** [comment]
Cara, eu tenho este aqui:

![Livro MongoDB](http://novatec.com.br/figuras/capas/9788575224229.gif)

http://novatec.com.br/livros/mongodb/

**Comment by leonascimento** [comment]
Vou comprá-lo vlw pela indicação @wbruno.
